site_name: Indian Penal Code
repo_url: https://github.com/patashale/ipc
repo_name: patashale/ipc
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.footer

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/patashale
      name: Patashale on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/patashale
      name: Patashale on GitHub

nav:
  - Know before you start: index.md

copyright: Copyright &copy; 2023 Patashale
