site_name: Indian Penal Code
repo_url: https://github.com/patashale/ipc
repo_name: patashale/ipc
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.footer

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/patashale
      name: Patashale™ on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/patashale
      name: Patashale™ on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/patashale_in
      name: Patashale™ on Twitter
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@patashale
      name: Patashale™ on Mastodon Social
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@patashale
      name: Patashale™ on Fosstodon

nav:
  - Know before you start: index.md
  - Chapter 1 - Introduction: 
    - Preamble: en/preamble.md
    - IPC 1: en/1.md
    - IPC 2: en/2.md
    - IPC 3: en/3.md
    - IPC 4: en/4.md
    - IPC 5: en/5.md
  - Chapter 2 - General Explanations:
    - IPC 6: en/6.md
    - IPC 7: en/7.md
    - IPC 8: en/8.md
    - IPC 9: en/9.md
    - IPC 10: en/10.md
    - IPC 11: en/11.md
    - IPC 12: en/12.md
    - IPC 14: en/14.md
    - IPC 17: en/17.md
    - IPC 18: en/18.md
    - IPC 19: en/19.md
    - IPC 20: en/20.md
    - IPC 21: en/21.md
    - IPC 22: en/22.md
    - IPC 23: en/23.md
    - IPC 24: en/24.md
    - IPC 25: en/25.md
    - IPC 26: en/26.md
    - IPC 27: en/27.md
    - IPC 28: en/28.md
    - IPC 29: en/29.md
    - IPC 29A: en/29A.md
    - IPC 30: en/30.md
    - IPC 31: en/31.md
    - IPC 32: en/32.md
    - IPC 33: en/33.md
    - IPC 34: en/34.md
    - IPC 35: en/35.md
    - IPC 36: en/36.md
    - IPC 37: en/37.md
    - IPC 38: en/38.md
    - IPC 39: en/39.md
    - IPC 40: en/40.md
    - IPC 41: en/41.md
    - IPC 42: en/42.md
    - IPC 43: en/43.md
    - IPC 44: en/44.md
    - IPC 45: en/45.md
    - IPC 46: en/46.md
    - IPC 47: en/47.md
    - IPC 48: en/48.md
    - IPC 49: en/49.md
    - IPC 50: en/50.md
    - IPC 51: en/51.md
    - IPC 52: en/52.md
    - IPC 52A: en/52A.md
  - Chapter 3 - Punishments:
    - IPC 53: en/53.md
    - IPC 53A: en/53A.md
    - IPC 54: en/54.md
    - IPC 55: en/55.md
    - IPC 55A: en/55A.md
    - IPC 57: en/57.md
    - IPC 60: en/60.md
    - IPC 64: en/64.md
    - IPC 65: en/65.md
    - IPC 66: en/66.md
    - IPC 67: en/67.md
    - IPC 68: en/68.md
    - IPC 69: en/69.md
    - IPC 70: en/70.md
    - IPC 71: en/71.md
    - IPC 72: en/72.md
    - IPC 73: en/73.md
    - IPC 74: en/74.md
    - IPC 75: en/75.md
  - Chapter 4 - General Exceptions:
    - IPC 76: en/76.md
    - IPC 77: en/77.md
    - IPC 78: en/78.md
    - IPC 79: en/79.md
    - IPC 80: en/80.md
    - IPC 81: en/81.md
    - IPC 82: en/82.md
    - IPC 83: en/83.md
    - IPC 84: en/84.md
    - IPC 85: en/85.md
    - IPC 86: en/86.md
    - IPC 87: en/87.md
    - IPC 88: en/88.md
    - IPC 89: en/89.md
    - IPC 90: en/90.md
    - IPC 91: en/91.md
    - IPC 92: en/92.md
    - IPC 93: en/93.md
    - IPC 94: en/94.md
    - IPC 95: en/95.md
    - IPC 96: en/96.md
    - IPC 97: en/97.md
    - IPC 98: en/98.md
    - IPC 99: en/99.md
    - IPC 100: en/100.md
    - IPC 101: en/101.md
    - IPC 102: en/102.md
    - IPC 103: en/103.md
    - IPC 104: en/104.md
    - IPC 105: en/105.md
    - IPC 106: en/106.md

copyright: <a property="dct:title" rel="cc:attributionURL" href="https://www.patashale.in/ipc">Indian Penal Code</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://www.github.com/patashale">Patashale™</a> is licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-SA 4.0</a> & <a href="https://www.gnu.org/licenses/agpl-3.0" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">AGPL 3.0</a>
