site_name: Indian Penal Code
repo_url: https://github.com/patashale/ipc
repo_name: patashale/ipc
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.footer

extra_css:
  - stylesheets/extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/patashale
      name: Patashale™ on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/patashale
      name: Patashale™ on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/patashale_in
      name: Patashale™ on Twitter
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@patashale
      name: Patashale™ on Mastodon Social
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@patashale
      name: Patashale™ on Fosstodon

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Know before you start: index.md
  - Chapter 1 - Introduction: 
    - Preamble: en/preamble.md
    - IPC 1: en/1.md
    - IPC 2: en/2.md
    - IPC 3: en/3.md
    - IPC 4: en/4.md
    - IPC 5: en/5.md
  - Chapter 2 - General Explanations:
    - IPC 6: en/6.md
    - IPC 7: en/7.md
    - IPC 8: en/8.md
    - IPC 9: en/9.md
    - IPC 10: en/10.md
    - IPC 11: en/11.md
    - IPC 12: en/12.md
    - IPC 14: en/14.md
    - IPC 17: en/17.md
    - IPC 18: en/18.md
    - IPC 19: en/19.md
    - IPC 20: en/20.md
    - IPC 21: en/21.md
    - IPC 22: en/22.md
    - IPC 23: en/23.md
    - IPC 24: en/24.md
    - IPC 25: en/25.md
    - IPC 26: en/26.md
    - IPC 27: en/27.md
    - IPC 28: en/28.md
    - IPC 29: en/29.md
    - IPC 29A: en/29A.md
    - IPC 30: en/30.md
    - IPC 31: en/31.md
    - IPC 32: en/32.md
    - IPC 33: en/33.md
    - IPC 34: en/34.md
    - IPC 35: en/35.md
    - IPC 36: en/36.md
    - IPC 37: en/37.md
    - IPC 38: en/38.md
    - IPC 39: en/39.md
    - IPC 40: en/40.md
    - IPC 41: en/41.md
    - IPC 42: en/42.md
    - IPC 43: en/43.md
    - IPC 44: en/44.md
    - IPC 45: en/45.md
    - IPC 46: en/46.md
    - IPC 47: en/47.md
    - IPC 48: en/48.md
    - IPC 49: en/49.md
    - IPC 50: en/50.md
    - IPC 51: en/51.md
    - IPC 52: en/52.md
    - IPC 52A: en/52A.md
  - Chapter 3 - Punishments:
    - IPC 53: en/53.md
    - IPC 53A: en/53A.md
    - IPC 54: en/54.md
    - IPC 55: en/55.md
    - IPC 55A: en/55A.md
    - IPC 57: en/57.md
    - IPC 60: en/60.md
    - IPC 63: en/63.md
    - IPC 64: en/64.md
    - IPC 65: en/65.md
    - IPC 66: en/66.md
    - IPC 67: en/67.md
    - IPC 68: en/68.md
    - IPC 69: en/69.md
    - IPC 70: en/70.md
    - IPC 71: en/71.md
    - IPC 72: en/72.md
    - IPC 73: en/73.md
    - IPC 74: en/74.md
    - IPC 75: en/75.md
  - Chapter 4 - General Exceptions:
    - IPC 76: en/76.md
    - IPC 77: en/77.md
    - IPC 78: en/78.md
    - IPC 79: en/79.md
    - IPC 80: en/80.md
    - IPC 81: en/81.md
    - IPC 82: en/82.md
    - IPC 83: en/83.md
    - IPC 84: en/84.md
    - IPC 85: en/85.md
    - IPC 86: en/86.md
    - IPC 87: en/87.md
    - IPC 88: en/88.md
    - IPC 89: en/89.md
    - IPC 90: en/90.md
    - IPC 91: en/91.md
    - IPC 92: en/92.md
    - IPC 93: en/93.md
    - IPC 94: en/94.md
    - IPC 95: en/95.md
    - IPC 96: en/96.md
    - IPC 97: en/97.md
    - IPC 98: en/98.md
    - IPC 99: en/99.md
    - IPC 100: en/100.md
    - IPC 101: en/101.md
    - IPC 102: en/102.md
    - IPC 103: en/103.md
    - IPC 104: en/104.md
    - IPC 105: en/105.md
    - IPC 106: en/106.md
  - Chapter 5 - Abetment:
    - IPC 107: en/107.md
    - IPC 108: en/108.md
    - IPC 108A: en/108A.md
    - IPC 109: en/109.md
    - IPC 110: en/110.md
    - IPC 111: en/111.md
    - IPC 112: en/112.md
    - IPC 113: en/113.md
    - IPC 114: en/114.md
    - IPC 115: en/115.md
    - IPC 116: en/116.md
    - IPC 117: en/117.md
    - IPC 118: en/118.md
    - IPC 119: en/119.md
    - IPC 120: en/120.md
  - Chapter 5A - Criminal Conspiracy:
    - IPC 120A: en/120A.md
    - IPC 120B: en/120B.md
  - Chapter 6 - Offences against the state:
    - IPC 121: en/121.md
    - IPC 121A: en/121A.md
    - IPC 122: en/122.md
    - IPC 123: en/123.md
    - IPC 124: en/124.md
    - IPC 124A: en/124A.md
    - IPC 125: en/125.md
    - IPC 126: en/126.md
    - IPC 127: en/127.md
    - IPC 128: en/128.md
    - IPC 129: en/129.md
    - IPC 130: en/130.md
  - Chapter 7 - Offences relating to the army, navy and air force:
    - IPC 131: en/131.md
    - IPC 132: en/132.md
    - IPC 133: en/133.md
    - IPC 134: en/134.md
    - IPC 135: en/135.md
    - IPC 136: en/136.md
    - IPC 137: en/137.md
    - IPC 138: en/138.md
    - IPC 139: en/139.md
    - IPC 140: en/140.md
  - Chapter 8 - Offences against the public tranquillity:
    - IPC 141: en/141.md
    - IPC 142: en/142.md
    - IPC 143: en/143.md
    - IPC 144: en/144.md
    - IPC 145: en/145.md
    - IPC 146: en/146.md
    - IPC 147: en/147.md
    - IPC 148: en/148.md
    - IPC 149: en/149.md
    - IPC 150: en/150.md
    - IPC 151: en/151.md
    - IPC 152: en/152.md
    - IPC 153: en/153.md
    - IPC 153A: en/153A.md
    - IPC 153AA: en/153AA.md
    - IPC 153B: en/153B.md
    - IPC 154: en/154.md
    - IPC 155: en/155.md
    - IPC 156: en/156.md
    - IPC 157: en/157.md
    - IPC 158: en/158.md
    - IPC 159: en/159.md
    - IPC 160: en/160.md
  - Chapter 9 - Offences by or relating to public servants:
    - IPC 166: en/166.md
    - IPC 166: en/166A.md
    - IPC 166: en/166B.md
    - IPC 167: en/167.md
    - IPC 168: en/168.md
    - IPC 169: en/169.md
    - IPC 170: en/170.md
    - IPC 171: en/171.md
  - Chapter 9A - Offences relating to elections:
    - IPC 171A: en/171A.md
    - IPC 171B: en/171B.md
    - IPC 171C: en/171C.md
    - IPC 171D: en/171D.md
    - IPC 171E: en/171E.md
    - IPC 171F: en/171F.md
    - IPC 171G: en/171G.md
    - IPC 171H: en/171H.md
    - IPC 171I: en/171I.md
  - Chapter 10 - Contempts of the lawful authority of public servants:
    - IPC 172: en/172.md
    - IPC 173: en/173.md
    - IPC 174: en/174.md
    - IPC 174A: en/174A.md
    - IPC 175: en/175.md
    - IPC 176: en/176.md
    - IPC 177: en/177.md
    - IPC 178: en/178.md
    - IPC 179: en/179.md
    - IPC 180: en/180.md
    - IPC 181: en/181.md
    - IPC 182: en/182.md
    - IPC 183: en/183.md
    - IPC 184: en/184.md
    - IPC 185: en/185.md
    - IPC 186: en/186.md
    - IPC 187: en/187.md
    - IPC 188: en/188.md
    - IPC 189: en/189.md
    - IPC 190: en/190.md
  - Chapter 11 - False evidence and offences against public justice:
    - IPC 191: en/191.md
    - IPC 192: en/192.md
    - IPC 193: en/193.md
    - IPC 194: en/194.md
    - IPC 195: en/195.md
    - IPC 195A: en/195A.md
    - IPC 196: en/196.md
    - IPC 197: en/197.md
    - IPC 198: en/198.md
    - IPC 199: en/199.md
    - IPC 200: en/200.md
    - IPC 201: en/201.md
    - IPC 202: en/202.md
    - IPC 203: en/203.md
    - IPC 204: en/204.md
    - IPC 205: en/205.md
    - IPC 206: en/206.md
    - IPC 207: en/207.md
    - IPC 208: en/208.md
    - IPC 209: en/209.md
    - IPC 210: en/210.md
    - IPC 211: en/211.md
    - IPC 212: en/212.md
    - IPC 213: en/213.md
    - IPC 214: en/214.md
    - IPC 215: en/215.md
    - IPC 216: en/216.md
    - IPC 216A: en/216A.md
    - IPC 217: en/217.md
    - IPC 218: en/218.md
    - IPC 219: en/219.md
    - IPC 220: en/220.md
    - IPC 221: en/221.md
    - IPC 222: en/222.md
    - IPC 223: en/223.md
    - IPC 224: en/224.md
    - IPC 225: en/225.md
    - IPC 225A: en/225A.md
    - IPC 225B: en/225B.md
    - IPC 227: en/227.md
    - IPC 228: en/228.md
    - IPC 228A: en/228A.md
    - IPC 229: en/229.md
    - IPC 229A: en/229A.md
  - Chapter 12 - Offences relating to coin and government stamps:
    - IPC 230: en/230.md
    - IPC 231: en/231.md
    - IPC 232: en/232.md
    - IPC 233: en/233.md
    - IPC 234: en/234.md
    - IPC 235: en/235.md
    - IPC 236: en/236.md
    - IPC 237: en/237.md
    - IPC 238: en/238.md
    - IPC 239: en/239.md
    - IPC 240: en/240.md
    - IPC 241: en/241.md
    - IPC 242: en/242.md
    - IPC 243: en/243.md
    - IPC 244: en/244.md
    - IPC 245: en/245.md
    - IPC 246: en/246.md
    - IPC 247: en/247.md
    - IPC 248: en/248.md
    - IPC 249: en/249.md
    - IPC 250: en/250.md
    - IPC 251: en/251.md
    - IPC 252: en/252.md
    - IPC 253: en/253.md
    - IPC 254: en/254.md
    - IPC 255: en/255.md
    - IPC 256: en/256.md
    - IPC 257: en/257.md
    - IPC 258: en/258.md
    - IPC 259: en/259.md
    - IPC 260: en/260.md
    - IPC 261: en/261.md
    - IPC 262: en/262.md
    - IPC 263: en/263.md
    - IPC 263A: en/263A.md
  - Chapter 13 - Offences relating to weights and measures:
    - IPC 264: en/264.md
    - IPC 265: en/265.md
    - IPC 266: en/266.md
    - IPC 267: en/267.md
  - Chapter 14 - Offences the public health, safety, convenience, decency and morals:
    - IPC 268: en/268.md
    - IPC 269: en/269.md
    - IPC 270: en/270.md
    - IPC 271: en/271.md
    - IPC 272: en/272.md
    - IPC 273: en/273.md
    - IPC 274: en/274.md
    - IPC 275: en/275.md
    - IPC 276: en/276.md
    - IPC 277: en/277.md
    - IPC 278: en/278.md
    - IPC 279: en/279.md
    - IPC 280: en/280.md
    - IPC 281: en/281.md
    - IPC 282: en/282.md
    - IPC 283: en/283.md
    - IPC 284: en/284.md
    - IPC 285: en/285.md
    - IPC 286: en/286.md
    - IPC 287: en/287.md
    - IPC 288: en/288.md
    - IPC 289: en/289.md
    - IPC 289A: en/289A.md
    - IPC 290: en/290.md
    - IPC 291: en/291.md
    - IPC 292: en/292.md
    - IPC 292A: en/292A.md
    - IPC 293: en/293.md
    - IPC 294: en/294.md
    - IPC 294A: en/294A.md
  - Chapter 15 - Offences relating to religion:
    - IPC 295: en/295.md
    - IPC 295A: en/295A.md
    - IPC 296: en/296.md
    - IPC 297: en/297.md
    - IPC 298: en/298.md
  - Chapter 16 - Offences affecting the human body:
    - Offences affecting life:
      - IPC 299: en/299.md
      - IPC 300: en/300.md
      - IPC 301: en/301.md
      - IPC 302: en/302.md
      - IPC 303: en/303.md
      - IPC 304: en/304.md
      - IPC 304A: en/304A.md
      - IPC 304A: en/304AA.md
      - IPC 304B: en/304B.md
      - IPC 305: en/305.md
      - IPC 306: en/306.md
      - IPC 307: en/307.md
      - IPC 308: en/308.md
      - IPC 309: en/309.md
      - IPC 310: en/310.md
      - IPC 311: en/311.md
    - Offences affecting miscarriage, injuries to unborn children, exposure of infants and concealment of births:
      - IPC 312: en/312.md
      - IPC 313: en/313.md
      - IPC 314: en/314.md
      - IPC 315: en/315.md
      - IPC 316: en/316.md
      - IPC 317: en/317.md
      - IPC 318: en/318.md
    - Hurt:
      - IPC 319: en/319.md
      - IPC 320: en/320.md
      - IPC 321: en/321.md
      - IPC 322: en/322.md
      - IPC 323: en/323.md
      - IPC 324: en/324.md
      - IPC 325: en/325.md
      - IPC 326: en/326.md
      - IPC 326A: en/326A.md
      - IPC 326B: en/326B.md
      - IPC 327: en/327.md
      - IPC 328: en/328.md
      - IPC 329: en/329.md
      - IPC 330: en/330.md   
      - IPC 331: en/331.md
      - IPC 332: en/332.md
      - IPC 333: en/333.md
      - IPC 334: en/334.md
      - IPC 335: en/335.md
      - IPC 336: en/336.md
      - IPC 337: en/337.md
      - IPC 338: en/338.md
    - Wrongful restraint and confinement:
      - IPC 339: en/339.md
      - IPC 340: en/340.md
      - IPC 341: en/341.md
      - IPC 342: en/342.md
      - IPC 343: en/343.md
      - IPC 344: en/344.md
      - IPC 345: en/345.md
      - IPC 346: en/346.md
      - IPC 347: en/347.md
      - IPC 348: en/348.md
    - Criminal force and assault:
      - IPC 349: en/349.md
      - IPC 350: en/350.md
      - IPC 351: en/351.md
      - IPC 352: en/352.md
      - IPC 353: en/353.md
      - IPC 354: en/354.md
      - IPC 354A: en/354A.md
      - IPC 354B: en/354B.md
      - IPC 354C: en/354C.md
      - IPC 354D: en/354D.md
      - IPC 354D: en/354E.md
      - IPC 355: en/355.md
      - IPC 356: en/356.md
      - IPC 357: en/357.md
      - IPC 358: en/358.md
    - Kidnapping, abduction, slavery and forced labour:
      - IPC 359: en/359.md
      - IPC 360: en/360.md
      - IPC 361: en/361.md
      - IPC 362: en/362.md
      - IPC 363: en/363.md
      - IPC 363A: en/363A.md
      - IPC 364: en/364.md
      - IPC 364A: en/364A.md
      - IPC 365: en/365.md
      - IPC 366: en/366.md
      - IPC 366A: en/366A.md
      - IPC 366B: en/366B.md
      - IPC 367: en/367.md
      - IPC 368: en/368.md
      - IPC 369: en/369.md
      - IPC 370: en/370.md
      - IPC 370A: en/370A.md
      - IPC 371: en/371.md
      - IPC 372: en/372.md
      - IPC 373: en/373.md
      - IPC 374: en/374.md
    - Sexual offences:
      - IPC 375: en/375.md
      - IPC 376: en/376.md
      - IPC 376A: en/376A.md
      - IPC 376A: en/376AA.md
      - IPC 376AB: en/376AB.md
      - IPC 376B: en/376B.md
      - IPC 376C: en/376C.md
      - IPC 376D: en/376D.md
      - IPC 376DA: en/376DA.md
      - IPC 376DB: en/376DB.md
      - IPC 376E: en/376E.md
      - IPC 376F: en/376F.md
    - Unnatural offences:
      - IPC 377: en/377.md
  - Chapter 17 - Offences against property:
    - Theft:
      - IPC 378: en/378.md
      - IPC 379: en/379.md
      - IPC 379A: en/379A.md
      - IPC 379B: en/379B.md
      - IPC 380: en/380.md
      - IPC 381: en/381.md
      - IPC 382: en/382.md
      - IPC 382A: en/382A.md
      - IPC 382B: en/382B.md
      - IPC 382C: en/382C.md
      - IPC 382D: en/382D.md
      - IPC 382E: en/382E.md
      - IPC 382F: en/382F.md
    - Extortion:
      - IPC 383: en/383.md
      - IPC 384: en/384.md
      - IPC 385: en/385.md
      - IPC 386: en/386.md
      - IPC 387: en/387.md
      - IPC 388: en/388.md
      - IPC 389: en/389.md
    - Robbery and Dacoity:
      - IPC 390: en/390.md
      - IPC 391: en/391.md
      - IPC 392: en/392.md
      - IPC 393: en/393.md
      - IPC 394: en/394.md
      - IPC 395: en/395.md
      - IPC 396: en/396.md
      - IPC 397: en/397.md
      - IPC 398: en/398.md
      - IPC 399: en/399.md
      - IPC 400: en/400.md
      - IPC 401: en/401.md
      - IPC 402: en/402.md
      - IPC 403: en/403.md
      - IPC 404: en/404.md
    - Criminal breach of trust:
      - IPC 405: en/405.md
      - IPC 406: en/406.md
      - IPC 407: en/407.md
      - IPC 408: en/408.md
      - IPC 409: en/409.md
    - Receiving of stolen property:
      - IPC 410: en/410.md
      - IPC 411: en/411.md
      - IPC 412: en/412.md
      - IPC 413: en/413.md
      - IPC 414: en/414.md
    - Cheating:
      - IPC 415: en/415.md
      - IPC 416: en/416.md
      - IPC 417: en/417.md
      - IPC 418: en/418.md
      - IPC 419: en/419.md
      - IPC 420: en/420.md
    - Fraudulent deeds and dispositions of property:
      - IPC 421: en/421.md
      - IPC 422: en/422.md
      - IPC 423: en/423.md
      - IPC 424: en/424.md
    - Mischief:
      - IPC 425: en/425.md
      - IPC 426: en/426.md
      - IPC 427: en/427.md
      - IPC 428: en/428.md
      - IPC 429: en/429.md
      - IPC 430: en/430.md
      - IPC 431: en/431.md
      - IPC 432: en/432.md
      - IPC 433: en/433.md
      - IPC 434: en/434.md
      - IPC 435: en/435.md
      - IPC 436: en/436.md
      - IPC 437: en/437.md
      - IPC 438: en/438.md
      - IPC 439: en/439.md
      - IPC 440: en/440.md
    - Criminal Trespass:
      - IPC 441: en/441.md
      - IPC 442: en/442.md
      - IPC 443: en/443.md
      - IPC 444: en/444.md
      - IPC 445: en/445.md
      - IPC 446: en/446.md
      - IPC 447: en/447.md
      - IPC 448: en/448.md
      - IPC 449: en/449.md
      - IPC 450: en/450.md
      - IPC 451: en/451.md
      - IPC 452: en/452.md
      - IPC 453: en/453.md
      - IPC 454: en/454.md
      - IPC 455: en/455.md
      - IPC 456: en/456.md
      - IPC 457: en/457.md
      - IPC 458: en/458.md
      - IPC 459: en/459.md
      - IPC 460: en/460.md
      - IPC 461: en/461.md
      - IPC 462: en/462.md
  - Chapter 18 - Offences relating to documents and to property marks:
    - IPC 463: en/463.md
    - IPC 464: en/464.md
    - IPC 465: en/465.md
    - IPC 466: en/466.md
    - IPC 467: en/467.md
    - IPC 468: en/468.md
    - IPC 469: en/469.md
    - IPC 470: en/470.md
    - IPC 471: en/471.md
    - IPC 472: en/472.md
    - IPC 473: en/473.md
    - IPC 474: en/474.md
    - IPC 475: en/475.md
    - IPC 476: en/476.md
    - IPC 477: en/477.md
    - IPC 477A: en/477A.md
    - Property and other marks:
      - IPC 479: en/479.md
      - IPC 481: en/481.md
      - IPC 482: en/482.md
      - IPC 483: en/483.md
      - IPC 484: en/484.md
      - IPC 485: en/485.md
      - IPC 486: en/486.md
      - IPC 487: en/487.md
      - IPC 488: en/488.md
      - IPC 489: en/489.md
    - Currency notes and bank notes:
      - IPC 489A: en/489A.md
      - IPC 489B: en/489B.md
      - IPC 489C: en/489C.md
      - IPC 489D: en/489D.md
      - IPC 489E: en/489E.md
  - Chapter 19 - The criminal breach of contracts of service:
    - IPC 491: en/491.md
  - Chapter 20 - Offences relating to marriage:
    - IPC 493: en/493.md
    - IPC 494: en/494.md
    - IPC 495: en/495.md
    - IPC 496: en/496.md
    - IPC 497: en/497.md
    - IPC 498: en/498.md
  - Chapter 20A - Cruelty by husband or relatives of husband:
    - IPC 498A: en/498A.md
  - Chapter 21 - Defamation:
    - IPC 499: en/499.md
    - IPC 500: en/500.md
    - IPC 501: en/501.md
    - IPC 502: en/502.md



copyright: <a property="dct:title" rel="cc:attributionURL" href="https://www.patashale.in/ipc">Indian Penal Code</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://www.github.com/patashale">Patashale™</a> is licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-SA 4.0</a> & <a href="https://www.gnu.org/licenses/agpl-3.0" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">AGPL 3.0</a>
